name: Python build application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.2"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQT5 g4f curl_cffi
        pip install pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Build Linux
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon "ui/icon.ico" --name "ChatGPTFree-App-linux" --add-data "ui/:ui/"  "main.py"
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ChatGPTFree-App-linux
        path: dist/ChatGPTFree-App-linux

    - name: Commit and Push Built App
      run: |
        cd dist
        cp ChatGPTFree-App-linux ../ChatGPTFree-App-linux
        git config --global user.name 'marakhd'
        git config --global user.email 'marakin09@mail.ru'
        git pull --rebase origin main
        git add ChatGPTFree-App-linux
        git commit -m 'Add build application Linux' || echo "Nothing to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.2"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQT5 g4f curl_cffi
        pip install pyinstaller
        pip install -r requirements.txt
        
    - name: Build Windows
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon "ui/icon.ico" --name "ChatGPTFree-App-windows" --add-data "ui/:ui/"  "main.py"

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ChatGPTFree-App-windows.exe
        path: dist/ChatGPTFree-App-windows.exe

    - name: Commit and Push Built App
      run: |
        cd dist
        cp ChatGPTFree-App-windows.exe ../ChatGPTFree-App-windows.exe
        git config --global user.name 'marakhd'
        git config --global user.email 'marakin09@mail.ru'
        git pull --rebase origin main
        git add ChatGPTFree-App-windows
        git commit -m 'Add build application Windows' || echo "Nothing to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.12.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.2"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQT5 g4f curl_cffi
        pip install pyinstaller
        pip install Pillow
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Build macOS
      run: |
        pyinstaller --noconfirm --onefile --windowed --icon "ui/icon.icns" --name "ChatGPTFree-App-macos" --add-data "ui/:ui/"  "main.py"
        
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ChatGPTFree-App.macOS
        path: dist/ChatGPTFree-App.macos

    - name: Commit and Push Built App
      run: |
        cd dist
        cp ChatGPTFree-App-macos ../ChatGPTFree-App-macos
        git config --global user.name 'marakhd'  # Укажите ваше имя
        git config --global user.email 'marakin09@mail.ru'  # Укажите ваш email
        git pull --rebase origin main
        git add ChatGPTFree-App-macos
        git commit -m 'Add build application macOS' || echo "Nothing to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
